### PR TITLE
More exception

### PR DESCRIPTION
**Pull request by Ilithy**

### CODE REVIEW

**Comment by Raj9039852537** [comment]
Can you explain ano and bit. Is they for normal sites or for special protocols like onion Loki etc.

**Comment by Ilithy** [comment]
Yes of course, sorry, I should have documented my PR better, it is about secure protocols such as Tor, i2p lokinet etc...
.ano for [Anonet](http://www.anonet.org/)
.bit for [Zeronet](https://zeronet.io/)

**Comment by Raj9039852537** [comment]
Ok 
[Added](https://github.com/Raj9039852537/urlChecker-patternchecker-config/commit/a55af7f4775629694000a816218b71916fc8e5e7)  new "comments" string in the JSON to explain something where needed. It is optional.

**Comment by Ilithy** [comment]
Great idea thanks 🙏

**Pull request merged**
